name: Publish Linux/x64 binaries

on:
  push:
    tags:
      - v0.*
      - v0.*.*
      - v1.*
      - v1.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew jpackageZip
      - name: Create Release
        uses: ncipollo/release-action@v1.6.1
        id: create_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replaceArtifacts: false
          body: Fully automated release
          artifacts: "./build/distributions/openrndr-application-linux-x64.zip"